name: Run pytest

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set PYTHONPATH
        run: |
           export PYTHONPATH=$PYTHONPATH:/home/runner/work/sort-analyzer/sort-analyzer/algorithms
      - name: Install dependencies
        run: |
          pip install pytest
      - name: Run pytest
        run: |
          pytest